export const buildings = [
  { name: "Cursor", cost: 15, cps: 0.1, cost_multiplier: 1.15,
    desc: "Autoclicks once every 10 seconds.",
    flavor: "Every journey starts with a single click. Or, in this case, a robotic finger doing it for you while you eat Doritos." },
  { name: "Grandma", cost: 100, cps: 1, cost_multiplier: 1.15,
    requires: [{ type: "totalCookies", min: 50 }],
    desc: "A nice grandma to bake more cookies.",
    flavor: "She's been baking nonstop for 72 hours. Someone should check on her. Don't." },
  { name: "Farm", cost: 1100, cps: 8, cost_multiplier: 1.15,
    requires: [{ type: "totalBuildings", min: 5 }, { type: "totalCookies", min: 500 }],
    desc: "Grows cookie plants from magic seeds.",
    flavor: "The FDA has concerns about cookies growing on trees. You have concerns about the FDA finding your farm." },
  { name: "Factory", cost: 12000, cps: 47, cost_multiplier: 1.15,
    requires: [{ type: "totalBuildings", min: 15 }, { type: "totalCookies", min: 5000 }],
    desc: "Produces large quantities of cookies.",
    flavor: "Child labor laws are merely a suggestion when the children are made of dough." },
  { name: "Mine", cost: 130000, cps: 260, cost_multiplier: 1.15,
    requires: [{ type: "totalBuildings", min: 30 }, { type: "totalCookies", min: 50000 }],
    desc: "Mines out cookie dough and sugar deposits.",
    flavor: "Deep beneath the earth, miners extract pure cookie dough. OSHA stopped returning our calls." },
  { name: "Shipment", cost: 1400000, cps: 1400, cost_multiplier: 1.16,
    requires: [{ type: "totalBuildings", min: 50 }, { type: "totalCookies", min: 500000 }],
    desc: "Brings in cookies from the Cookie Planet.",
    flavor: "Turns out there's an entire planet made of cookies. NASA is furious we found it first." },
  { name: "Alchemy Lab", cost: 20000000, cps: 7800, cost_multiplier: 1.16,
    requires: [{ type: "totalBuildings", min: 80 }, { type: "totalCookies", min: 5000000 }],
    desc: "Turns gold into cookies.",
    flavor: "Finally, a use for alchemy that doesn't disappoint. Except the alchemists. They wanted gold. They got cookies." },
  { name: "Portal", cost: 330000000, cps: 44000, cost_multiplier: 1.17,
    requires: [{ type: "totalBuildings", min: 120 }, { type: "totalCookies", min: 100000000 }],
    desc: "Opens a door to the Cookieverse.",
    flavor: "The portal screams sometimes. We've decided that's normal and not at all a health code violation." },
  { name: "Time Machine", cost: 5100000000, cps: 260000, cost_multiplier: 1.17,
    requires: [{ type: "totalBuildings", min: 180 }, { type: "totalCookies", min: 1000000000 }, { type: "cps", min: 50000 }],
    desc: "Brings cookies from the past.",
    flavor: "We keep stealing cookies from the past. The timeline is in shambles but the profit margins are immaculate." },
  { name: "Antimatter Condenser", cost: 75000000000, cps: 1600000, cost_multiplier: 1.18,
    requires: [{ type: "totalBuildings", min: 280 }, { type: "totalCookies", min: 20000000000 }, { type: "cps", min: 500000 }],
    desc: "Condenses antimatter into cookies.",
    flavor: "Could destroy the known universe, but instead we're making snacks. Priorities." },
  { name: "Prism", cost: 1000000000000, cps: 10000000, cost_multiplier: 1.18,
    requires: [{ type: "totalBuildings", min: 400 }, { type: "totalCookies", min: 250000000000 }, { type: "cps", min: 5000000 }],
    desc: "Converts light itself into cookies.",
    flavor: "The sun works for us now. It doesn't know. Please don't tell it." },
  { name: "Chancemaker", cost: 26000000000000, cps: 67000000, cost_multiplier: 1.19,
    requires: [{ type: "totalBuildings", min: 550 }, { type: "totalCookies", min: 5000000000000 }, { type: "cps", min: 25000000 }],
    desc: "Generates cookies from sheer luck.",
    flavor: "Statistically impossible. Practically delicious. Our lawyer says to stop asking questions." },
  { name: "Fractal Engine", cost: 510000000000000, cps: 420000000, cost_multiplier: 1.20,
    requires: [{ type: "totalBuildings", min: 700 }, { type: "totalCookies", min: 100000000000000 }, { type: "cps", min: 200000000 }],
    desc: "Turns cookies into even more cookies.",
    flavor: "Each cookie contains a smaller cookie, which contains an even smaller cookie. It's cookies all the way down." },
];

export const upgrades = [
  // === Click Multipliers ===
  {
    name: "Better Click", cost: 100,
    effect: "Increase clicking power by 35%",
    type: "clickMultiplier", multiplier: 1.35,
    max_level: 15, cost_multiplier: 6,
    accel_start: 12, cost_acceleration: 3,
    prestige_bonus_levels: 2, prestige_cost_multiplier: 25,
    requires: [{ type: "totalClicks", min: 100 }]
  },

  // === Tiered Click Upgrade ===
  {
    type: "tieredUpgrade",
    tiers: [
      { name: "Iron Touch", effect: "Clicking gives 2x cookies", multiplier: 2, cost: 50000, buildingsRequired: 50 },
      { name: "Silver Touch", effect: "Clicking gives 2x cookies", multiplier: 2, cost: 2500000, buildingsRequired: 125 },
      { name: "Golden Touch", effect: "Clicking gives 2x cookies", multiplier: 2, cost: 50000000, buildingsRequired: 250 },
      { name: "Platinum Touch", effect: "Clicking gives 2x cookies", multiplier: 2, cost: 2500000000, buildingsRequired: 500 },
      { name: "Diamond Touch", effect: "Clicking gives 2x cookies", multiplier: 2, cost: 250000000000, buildingsRequired: 800 },
    ]
  },

  // === Building Boosts ===
  { name: "Efficient Grandmas", cost: 3000, effect: "Grandmas produce 50% more", type: "buildingBoost", target: "Grandma", multiplier: 1.50, max_level: 8, cost_multiplier: 5,
    accel_start: 5, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 15,
    requires: [{ type: "building", name: "Grandma", min: 10 }] },
  { name: "Farm Expansion", cost: 30000, effect: "Farms produce 50% more", type: "buildingBoost", target: "Farm", multiplier: 1.50, max_level: 8, cost_multiplier: 5,
    accel_start: 5, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 15,
    requires: [{ type: "building", name: "Farm", min: 10 }] },
  { name: "Factory Overdrive", cost: 500000, effect: "Factories are 2x as efficient", type: "buildingBoost", target: "Factory", multiplier: 2, max_level: 7, cost_multiplier: 7,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 20,
    requires: [{ type: "building", name: "Factory", min: 15 }] },
  { name: "Mine Boost", cost: 3000000, effect: "Mines produce 2x as much", type: "buildingBoost", target: "Mine", multiplier: 2, max_level: 7, cost_multiplier: 6,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 20,
    requires: [{ type: "building", name: "Mine", min: 15 }] },
  { name: "Shipment Upgrade", cost: 15000000, effect: "Shipments are 2x as efficient", type: "buildingBoost", target: "Shipment", multiplier: 2, max_level: 7, cost_multiplier: 6,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 20,
    requires: [{ type: "building", name: "Shipment", min: 15 }] },
  { name: "Alchemy Lab Boost", cost: 200000000, effect: "Alchemy Labs produce 2x as much", type: "buildingBoost", target: "Alchemy Lab", multiplier: 2, max_level: 6, cost_multiplier: 8,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 25,
    requires: [{ type: "building", name: "Alchemy Lab", min: 15 }, { type: "totalBuildings", min: 100 }] },
  { name: "Portal Boost", cost: 3000000000, effect: "Portals are 2x as efficient", type: "buildingBoost", target: "Portal", multiplier: 2, max_level: 6, cost_multiplier: 8,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 25,
    requires: [{ type: "building", name: "Portal", min: 15 }, { type: "totalBuildings", min: 150 }] },
  { name: "Time Warp", cost: 50000000000, effect: "Time Machines are 2x as efficient", type: "buildingBoost", target: "Time Machine", multiplier: 2, max_level: 6, cost_multiplier: 10,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 30,
    requires: [{ type: "building", name: "Time Machine", min: 15 }, { type: "totalBuildings", min: 225 }] },
  { name: "Antimatter Boost", cost: 500000000000, effect: "Antimatter Condensers produce 2x", type: "buildingBoost", target: "Antimatter Condenser", multiplier: 2, max_level: 6, cost_multiplier: 10,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 30,
    requires: [{ type: "building", name: "Antimatter Condenser", min: 15 }, { type: "totalBuildings", min: 325 }] },
  { name: "Prism Enhancement", cost: 8000000000000, effect: "Prisms are 2x as efficient", type: "buildingBoost", target: "Prism", multiplier: 2, max_level: 6, cost_multiplier: 12,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 35,
    requires: [{ type: "building", name: "Prism", min: 15 }, { type: "totalBuildings", min: 450 }] },
  { name: "Lucky Day", cost: 150000000000000, effect: "Chancemakers produce 2x", type: "buildingBoost", target: "Chancemaker", multiplier: 2, max_level: 6, cost_multiplier: 12,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 35,
    requires: [{ type: "building", name: "Chancemaker", min: 15 }, { type: "totalBuildings", min: 600 }] },
  { name: "Fractal Boost", cost: 2500000000000000, effect: "Fractal Engines produce 2x", type: "buildingBoost", target: "Fractal Engine", multiplier: 2, max_level: 6, cost_multiplier: 15,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 40,
    requires: [{ type: "building", name: "Fractal Engine", min: 15 }, { type: "totalBuildings", min: 750 }] },

  // === Global CPS Multiplier ===
  { name: "Cookie Recipe", cost: 500000, effect: "All production +10%", type: "globalCpsMultiplier", multiplier: 1.10, max_level: 9, cost_multiplier: 12,
    accel_start: 6, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 25,
    requires: [{ type: "cps", min: 200 }, { type: "totalBuildings", min: 30 }] },
  { name: "Industrial Revolution", cost: 100000000, effect: "All production +25%", type: "globalCpsMultiplier", multiplier: 1.25, max_level: 6, cost_multiplier: 20,
    accel_start: 4, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 40,
    requires: [{ type: "cps", min: 50000 }, { type: "totalBuildings", min: 150 }] },
  { name: "Cookie Singularity", cost: 500000000000, effect: "All production +50%", type: "globalCpsMultiplier", multiplier: 1.50, max_level: 5, cost_multiplier: 100,
    accel_start: 3, cost_acceleration: 4,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 75,
    requires: [{ type: "cps", min: 5000000 }, { type: "totalBuildings", min: 350 }] },

  // === Synergy Upgrades (one building boosts another) ===
  { name: "Grandma's Farmhands", cost: 100000, effect: "Each Grandma adds +0.5 CPS to Farms", type: "synergy", source: "Grandma", target: "Farm", bonus: 0.5, max_level: 7, cost_multiplier: 8,
    accel_start: 5, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 20,
    requires: [{ type: "building", name: "Grandma", min: 15 }, { type: "building", name: "Farm", min: 15 }] },
  { name: "Factory Automation", cost: 5000000, effect: "Each Factory adds +2 CPS to Mines", type: "synergy", source: "Factory", target: "Mine", bonus: 2, max_level: 7, cost_multiplier: 8,
    accel_start: 5, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 20,
    requires: [{ type: "building", name: "Factory", min: 20 }, { type: "building", name: "Mine", min: 15 }] },
  { name: "Portal Network", cost: 5000000000, effect: "Each Portal adds +50 CPS to Shipments", type: "synergy", source: "Portal", target: "Shipment", bonus: 50, max_level: 7, cost_multiplier: 10,
    accel_start: 5, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 25,
    requires: [{ type: "building", name: "Portal", min: 15 }, { type: "building", name: "Shipment", min: 20 }] },
  { name: "Temporal Alchemy", cost: 100000000000, effect: "Each Time Machine adds +200 CPS to Alchemy Labs", type: "synergy", source: "Time Machine", target: "Alchemy Lab", bonus: 200, max_level: 7, cost_multiplier: 10,
    accel_start: 5, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 25,
    requires: [{ type: "building", name: "Time Machine", min: 15 }, { type: "building", name: "Alchemy Lab", min: 20 }] },
  { name: "Fractal Prisms", cost: 2000000000000000, effect: "Each Fractal Engine adds +50K CPS to Prisms", type: "synergy", source: "Fractal Engine", target: "Prism", bonus: 50000, max_level: 5, cost_multiplier: 15,
    accel_start: 3, cost_acceleration: 3,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 30,
    requires: [{ type: "building", name: "Fractal Engine", min: 10 }, { type: "building", name: "Prism", min: 20 }] },

  // === Cursor Scaling (Cursor CPS scales with total non-cursor buildings) ===
  { name: "Thousand Fingers", cost: 500000, effect: "Cursors gain +0.1 CPS per non-cursor building", type: "cursorScaling", bonus: 0.1, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "building", name: "Cursor", min: 50 }, { type: "totalBuildings", min: 75 }] },
  { name: "Million Fingers", cost: 100000000, effect: "Cursors gain +0.5 CPS per non-cursor building", type: "cursorScaling", bonus: 0.5, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "building", name: "Cursor", min: 100 }, { type: "totalBuildings", min: 200 }] },
  { name: "Billion Fingers", cost: 25000000000, effect: "Cursors gain +5 CPS per non-cursor building", type: "cursorScaling", bonus: 5, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "building", name: "Cursor", min: 150 }, { type: "totalBuildings", min: 400 }] },
  { name: "Trillion Fingers", cost: 5000000000000, effect: "Cursors gain +50 CPS per non-cursor building", type: "cursorScaling", bonus: 50, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "building", name: "Cursor", min: 200 }, { type: "totalBuildings", min: 600 }] },

  // === Lucky Click Chance ===
  { name: "Lucky Cookies", cost: 250000, effect: "1.5% chance for bonus cookies on click", type: "luckyChance", chance: 0.015, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "totalClicks", min: 1000 }] },
  { name: "Serendipity", cost: 50000000, effect: "+1.5% lucky click chance", type: "luckyChance", chance: 0.015, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "totalClicks", min: 5000 }, { type: "totalUpgradesPurchased", min: 15 }] },
  { name: "Fortune", cost: 10000000000, effect: "+2% lucky click chance", type: "luckyChance", chance: 0.02, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "totalClicks", min: 10000 }, { type: "achievements", min: 20 }] },
  { name: "Jackpot", cost: 1000000000000, effect: "+3% lucky click chance", type: "luckyChance", chance: 0.03, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "totalClicks", min: 25000 }, { type: "achievements", min: 30 }] },

  // === Click CPS Scaling (clicking gives % of CPS — keeps clicking relevant) ===
  { name: "Plastic Mouse", cost: 500000, effect: "Each click gains +1% of your CPS", type: "cpsClick", bonus: 0.01, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "totalClicks", min: 1000 }, { type: "totalBuildings", min: 50 }] },
  { name: "Bronze Mouse", cost: 50000000, effect: "Each click gains +2% of your CPS", type: "cpsClick", bonus: 0.02, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "totalClicks", min: 5000 }, { type: "totalBuildings", min: 150 }] },
  { name: "Silver Mouse", cost: 10000000000, effect: "Each click gains +2% of your CPS", type: "cpsClick", bonus: 0.02, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "totalClicks", min: 15000 }, { type: "totalBuildings", min: 300 }] },
  { name: "Golden Mouse", cost: 2000000000000, effect: "Each click gains +3% of your CPS", type: "cpsClick", bonus: 0.03, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "totalClicks", min: 30000 }, { type: "totalBuildings", min: 500 }] },
  { name: "Diamond Mouse", cost: 500000000000000, effect: "Each click gains +4% of your CPS", type: "cpsClick", bonus: 0.04, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "totalClicks", min: 50000 }, { type: "totalBuildings", min: 750 }] },

  // === Mini-Game Reward Bonus ===
  { name: "Game Master", cost: 500000, effect: "Minigame rewards +25%", type: "miniGameBonus", multiplier: 1.25, max_level: 8, cost_multiplier: 6,
    accel_start: 5, cost_acceleration: 2.5,
    prestige_bonus_levels: 1, prestige_cost_multiplier: 15,
    requires: [{ type: "miniGamesWon", min: 1 }] },

  // === Frenzy Duration ===
  { name: "Extended Frenzy", cost: 10000000, effect: "Frenzies last 50% longer", type: "frenzyDuration", bonus: 1.5, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "cps", min: 5000 }, { type: "totalCookies", min: 10000000 }] },
  { name: "Mega Frenzy", cost: 5000000000, effect: "Frenzies last 2x longer", type: "frenzyDuration", bonus: 2.0, max_level: 1, cost_multiplier: 1,
    requires: [{ type: "cps", min: 500000 }, { type: "prestige", min: 1 }] },

  // === Offline Production (tiered) ===
  {
    type: "tieredUpgrade",
    tiers: [
      { name: "Offline Production I", effect: "Offline production: 0.5x → 0.75x", multiplier: 0.75, cost: 100000, buildingsRequired: 50 },
      { name: "Offline Production II", effect: "Offline production: 0.75x → 1x", multiplier: 1, cost: 2000000, buildingsRequired: 125 },
      { name: "Offline Production III", effect: "Offline production: 1x → 1.5x", multiplier: 1.5, cost: 50000000, buildingsRequired: 250 },
      { name: "Offline Production IV", effect: "Offline production: 1.5x → 2x", multiplier: 2, cost: 2000000000, buildingsRequired: 400 },
      { name: "Offline Production V", effect: "Offline production: 2x → 3x", multiplier: 3, cost: 100000000000, buildingsRequired: 600 },
    ]
  },
];

// === Achievements ===
export const achievements = [
  // Cookie milestones
  { id: "bake_1k", name: "Apprentice Baker", desc: "Bake 1,000 cookies", type: "totalCookies", requirement: 1000 },
  { id: "bake_10k", name: "Journeyman Baker", desc: "Bake 10,000 cookies", type: "totalCookies", requirement: 10000 },
  { id: "bake_100k", name: "Master Baker", desc: "Bake 100,000 cookies", type: "totalCookies", requirement: 100000 },
  { id: "bake_1m", name: "Cookie Mogul", desc: "Bake 1 million cookies", type: "totalCookies", requirement: 1000000 },
  { id: "bake_100m", name: "Cookie Tycoon", desc: "Bake 100 million cookies", type: "totalCookies", requirement: 100000000 },
  { id: "bake_1b", name: "Cookie Empire", desc: "Bake 1 billion cookies", type: "totalCookies", requirement: 1000000000 },
  { id: "bake_100b", name: "Cookie Dynasty", desc: "Bake 100 billion cookies", type: "totalCookies", requirement: 100000000000 },
  { id: "bake_1t", name: "Cookie Universe", desc: "Bake 1 trillion cookies", type: "totalCookies", requirement: 1000000000000 },
  { id: "bake_100t", name: "Cookie Multiverse", desc: "Bake 100 trillion cookies", type: "totalCookies", requirement: 100000000000000 },

  // CPS milestones
  { id: "cps_10", name: "Slow Start", desc: "Reach 10 CPS", type: "cps", requirement: 10 },
  { id: "cps_100", name: "Getting There", desc: "Reach 100 CPS", type: "cps", requirement: 100 },
  { id: "cps_1k", name: "Cookie Stream", desc: "Reach 1,000 CPS", type: "cps", requirement: 1000 },
  { id: "cps_10k", name: "Cookie River", desc: "Reach 10,000 CPS", type: "cps", requirement: 10000 },
  { id: "cps_100k", name: "Cookie Flood", desc: "Reach 100,000 CPS", type: "cps", requirement: 100000 },
  { id: "cps_1m", name: "Cookie Tsunami", desc: "Reach 1 million CPS", type: "cps", requirement: 1000000 },
  { id: "cps_1b", name: "Cookie Singularity", desc: "Reach 1 billion CPS", type: "cps", requirement: 1000000000 },

  // Click milestones
  { id: "click_100", name: "Casual Clicker", desc: "Click 100 times", type: "totalClicks", requirement: 100 },
  { id: "click_1k", name: "Dedicated Clicker", desc: "Click 1,000 times", type: "totalClicks", requirement: 1000 },
  { id: "click_5k", name: "Click Enthusiast", desc: "Click 5,000 times", type: "totalClicks", requirement: 5000 },
  { id: "click_10k", name: "Click Master", desc: "Click 10,000 times", type: "totalClicks", requirement: 10000 },
  { id: "click_50k", name: "Click Legend", desc: "Click 50,000 times", type: "totalClicks", requirement: 50000 },
  { id: "click_100k", name: "Click God", desc: "Click 100,000 times", type: "totalClicks", requirement: 100000 },

  // Building milestones
  { id: "buildings_10", name: "Small Business", desc: "Own 10 buildings", type: "totalBuildings", requirement: 10 },
  { id: "buildings_50", name: "Growing Empire", desc: "Own 50 buildings", type: "totalBuildings", requirement: 50 },
  { id: "buildings_100", name: "Cookie Corporation", desc: "Own 100 buildings", type: "totalBuildings", requirement: 100 },
  { id: "buildings_200", name: "Cookie Conglomerate", desc: "Own 200 buildings", type: "totalBuildings", requirement: 200 },
  { id: "buildings_500", name: "Cookie Megacorp", desc: "Own 500 buildings", type: "totalBuildings", requirement: 500 },
  { id: "buildings_1000", name: "Cookie Monopoly", desc: "Own 1,000 buildings", type: "totalBuildings", requirement: 1000 },

  // Special
  { id: "all_buildings", name: "Diversified Portfolio", desc: "Own at least 1 of every building type", type: "allBuildingTypes", requirement: 1 },
  { id: "lucky_first", name: "Feeling Lucky", desc: "Trigger your first lucky click", type: "luckyClicks", requirement: 1 },
  { id: "lucky_50", name: "Luck of the Irish", desc: "Trigger 50 lucky clicks", type: "luckyClicks", requirement: 50 },
  { id: "frenzy_first", name: "Frenzy!", desc: "Trigger your first frenzy", type: "frenziesTriggered", requirement: 1 },
  { id: "frenzy_10", name: "Frenzy Fanatic", desc: "Trigger 10 frenzies", type: "frenziesTriggered", requirement: 10 },
  { id: "prestige_1", name: "Ascended", desc: "Prestige for the first time", type: "timesPrestiged", requirement: 1 },
  { id: "prestige_5", name: "Enlightened", desc: "Prestige 5 times", type: "timesPrestiged", requirement: 5 },
  { id: "hc_100", name: "Heavenly Baker", desc: "Earn 100 heavenly chips", type: "heavenlyChips", requirement: 100 },
  { id: "hc_1000", name: "Celestial Baker", desc: "Earn 1,000 heavenly chips", type: "heavenlyChips", requirement: 1000 },
  { id: "upgrades_10", name: "Upgrader", desc: "Purchase 10 upgrades", type: "totalUpgradesPurchased", requirement: 10 },
  { id: "upgrades_25", name: "Serial Upgrader", desc: "Purchase 25 upgrades", type: "totalUpgradesPurchased", requirement: 25 },
  { id: "upgrades_50", name: "Upgrade Addict", desc: "Purchase 50 upgrades", type: "totalUpgradesPurchased", requirement: 50 },

  // Building-specific milestones (moved from easter eggs)
  { id: "cursor_100", name: "Cursor Army", desc: "Own 100 Cursors clicking in perfect unison", type: "buildingCount", requirement: 100, buildingIndex: 0 },
  { id: "grandma_50", name: "Grandma Battalion", desc: "Own 50 Grandmas — that's not a bakery, that's an army", type: "buildingCount", requirement: 50, buildingIndex: 1 },

  // Play-style milestones (moved from easter eggs)
  { id: "speed_1k", name: "Speedrunner", desc: "Reach 1,000 CPS within 5 minutes of starting", type: "speedrunner", requirement: 1000 },
  { id: "devoted", name: "Devoted Clicker", desc: "Click the cookie 10,000 times", type: "totalClicks", requirement: 10000 },
  { id: "bulk_buyer", name: "Bulk Buyer", desc: "Buy 100 buildings at once — that's not shopping, that's a hostile takeover", type: "bulkBuyer", requirement: 1 },

  // Mini-game achievements
  { id: "mini_first", name: "Game Night", desc: "Win your first mini-game from the news ticker", type: "miniGamesWon", requirement: 1 },
  { id: "mini_all", name: "Arcade Master", desc: "Win all 5 different mini-games at least once", type: "miniGamesWon", requirement: 5 },
]; 