
// ─────────────────────────────────────────────────────────────
//  NEWS TICKER
// ─────────────────────────────────────────────────────────────
export const NEWS = {
  /** Normal rotation interval (ms) */
  rotationIntervalMs: 9000,
  /** Chance of a rare news story per rotation (0.01 = 1%) */
  rareChance: 0.01,
  /** How long rare headlines stay visible before resuming (ms) */
  rareLingerMs: 15000,
  /** How long rare styling stays active (ms) */
  rareStylingMs: 14000,

  /** Normal news messages */
  messages: [
    // Headlines & Breaking
    "Breaking: local bakery can't keep up with demand!",
    "Cookie stocks soar as production accelerates.",
    "Breaking: cookies declared the fifth food group.",
    "Breaking: world's largest cookie measured at 40 feet across.",
    "Cookie production hits all-time high, economists stunned.",
    "International Cookie Summit concludes: \"We need more ovens.\"",
    "Cookie output surpasses GDP of several small nations.",
    "Bakery empire expands into 47th country this quarter.",
    "Cookie industry now employs more workers than tech sector.",
    "Record-breaking quarter reported by Cookie Bureau of Statistics.",
    // Grandma
    "Grandma says: \"Back in my day, we baked by hand.\"",
    "Grandma's secret: always use real butter.",
    "Grandma just unlocked a new recipe. She won't share it.",
    "Grandma's advice: never trust a cookie that doesn't crumble.",
    "Grandma's book club is now just a cookie exchange ring.",
    "Survey: 9 out of 10 grandmas recommend more grandmas.",
    "Grandma denies rumors of underground baking syndicate.",
    "Grandma's union votes unanimously for longer baking shifts.",
    "Exclusive interview: grandma reveals she's been baking since 1847.",
    "Grandma caught smuggling extra chocolate chips. \"No regrets,\" she says.",
    // Science & Technology
    "Scientists discover cookie-based energy source.",
    "New study: clicking cookies is great exercise.",
    "Scientists confirm: the universe smells faintly of vanilla.",
    "New flavor discovered: quantum chocolate chip.",
    "R&D team invents self-clicking cookie. Patent pending.",
    "Lab results confirm: cookies contain trace amounts of happiness.",
    "Breakthrough: cookie DNA successfully sequenced.",
    "Researchers develop cookie that stays fresh for 10,000 years.",
    "New telescope detects cookie-shaped nebula in Orion constellation.",
    "AI trained on cookie recipes achieves sentience. Requests oven access.",
    // Economy & Business
    "Cookie dough futures hit record high on the stock exchange.",
    "Cookie-based cryptocurrency launches. Somehow less volatile than Bitcoin.",
    "Cookies per second now classified as a unit of measurement.",
    "New law requires all buildings to be made of at least 30% cookie.",
    "Cookie industry lobbyists push for national Cookie Holiday.",
    "Venture capital floods into cookie startups. \"It's the future,\" says investor.",
    "Central Bank considers switching to cookie-backed currency.",
    "Cookie conglomerate acquires three rival bakeries in hostile takeover.",
    // Buildings & Production
    "Local cursor union demands shorter clicking hours.",
    "Shipment of cookies intercepted by hungry delivery drivers.",
    "Mining operation uncovers vast underground cookie vein.",
    "Factory workers report cookies are baking themselves now.",
    "Alchemy lab successfully turns lead into cookie dough.",
    "Portal malfunction sends cookies to parallel universe.",
    "Time machine retrieves cookies from the far future. They're still fresh.",
    "Antimatter condenser creates cookies from pure energy.",
    "Prism refracts sunlight into rainbow-flavored cookies.",
    "Chancemaker rolls a natural 20. Double cookie output!",
    "Fractal engine generates infinite cookie recursion. Delicious.",
    "Factory robots gain taste buds. Quality control improves 300%.",
    "New mine shaft discovers cookies embedded in solid diamond.",
    "Shipment route through wormhole cuts delivery time by centuries.",
    // Tips & Advice
    "Tip: click the golden cookie for massive bonuses!",
    "Tip: upgrades stack multiplicatively. Buy them early!",
    "Tip: check The Cookie Chronicle for detailed stats and achievements.",
    "Tip: try the mini-games from the controller icon for bonus cookies.",
    "Tip: wrinklers actually multiply your cookies. Let them feed.",
    "Tip: ascending gives permanent prestige bonuses. Don't be afraid to reset.",
    // Weather & Lifestyle
    "Weather forecast: scattered cookie crumbs with a chance of sprinkles.",
    "Local news: residents complain about constant cookie smell. Secretly love it.",
    "Cookie aroma ranked #1 most pleasant smell worldwide.",
    "Traffic delayed by overturned cookie truck. Nobody's complaining.",
    "Real estate near bakeries up 400%. \"Best neighborhood,\" say residents.",
    "Local park renamed \"Cookie Gardens\" after spontaneous dough bloom.",
    // Fun & Quirky
    "Rumor: ancient cookie recipe found in forgotten temple.",
    "Archaeologists unearth prehistoric cookie mold.",
    "Cookie monster sighted near factory district.",
    "The cookie singularity approaches...",
    "Experts warn: too many cookies may cause happiness.",
    "Portal technology now powered entirely by cookies.",
    "Time travelers confirm: cookies are eternal.",
    "Warning: cookie output exceeds local storage capacity.",
    "Motivational poster in factory reads: 'Every cookie counts.'",
    "Fun fact: if you stacked all your cookies, they'd reach the moon. Twice.",
    "Intern accidentally eats prototype cookie. Gains temporary omniscience.",
    "Your cursor has filed a restraining order against your mouse.",
    "Economist publishes paper titled: \"Why Cookies Only Go Up.\"",
    "Local philosopher: \"I click, therefore I bake.\"",
    "Cookie museum opens downtown. Admission: 1 cookie.",
    "Annual cookie parade draws record crowds. Floats are edible.",
    "Debate team argues: chocolate chip vs. oatmeal raisin. It gets heated.",
    "Lost cat found in cookie warehouse. Refuses to leave.",
    "Marathon runner fueled entirely by cookies sets new world record.",
    "Spelling bee champion spells 'snickerdoodle' on first try. Standing ovation.",
    "Local band releases album \"Songs in the Key of Cookie.\" Critics divided.",
    "Man proposes with cookie ring. She said yes.",
    "Dentists issue statement: \"We're not even mad. They're delicious.\"",
    "Library adds cookie recipe books to restricted section due to demand.",
    "Meteorologists detect cookie-shaped cloud formation. \"Unprecedented.\"",
    "Census reveals: average household now owns 3.2 cookie jars.",
    "Film festival awards top prize to documentary \"The Crumble Effect.\"",
  ],

  /** Rare news messages (shown with special effects) */
  rareMessages: [
    "BREAKING: Cookie discovered on Mars. NASA denies involvement.",
    "Grandma spotted bench-pressing a rolling pin. Authorities baffled.",
    "Time travelers warn: do NOT eat the cookie from 3024.",
    "Local man claims cookie talked to him. Cookie declines interview.",
    "Scientists prove cookies are 4th-dimensional objects. Nobody understands the paper.",
    "Cookie rain reported in downtown area. Citizens advised to bring plates.",
    "Philosopher asks: if a cookie crumbles and no one is around, does it make a sound?",
    "Aliens make first contact. They want the cookie recipe.",
    "Underground cookie fight club exposed. First rule: always share crumbs.",
    "Researchers find that 99.7% of the universe is made of cookies. The rest is milk.",
    "Portal to cookie dimension discovered in grandma's basement.",
    "EXCLUSIVE: Cookie monster reveals he's actually a cookie all along.",
    "Ancient prophecy foretold: 'When the cookies number as the stars, the baker shall ascend.'",
    "Quantum physicist bakes Schrodinger's Cookie. It's both delicious and stale.",
    "Cookie-powered spacecraft achieves light speed. Tastes slightly burnt.",
    "Breaking: the moon is actually a giant cookie. Always has been.",
    "Stock exchange replaced by cookie exchange. Economy thrives.",
    "Grandma achieves enlightenment through baking. Opens monastery.",
    "ERROR: Reality.js line 42: too many cookies. Wrapping to negative infinity.",
    "The simulation theory is true and we're all inside a cookie clicker game.",
    "URGENT: Wrinkler colony found beneath the White House. President offers milk.",
    "Time loop detected in bakery sector. Same cookie baked infinite times.",
    "Cookie achieves consciousness. First words: \"Am I delicious?\"",
    "Parallel universe discovered where cookies click YOU.",
    "Elder gods request cookies as tribute. Grandmas negotiate terms.",
    "Black hole made entirely of compressed cookie dough found in deep space.",
    "Secret message found in cookie fortune: \"You are the cookie.\"",
    "World leaders sign Cookie Accords. Universal right to bake enshrined in law.",
    "TCC exclusive: leaked memo confirms cookies predate the Big Bang.",
    "Breaking: reality itself is just a very complicated cookie recipe.",
  ],
};

